import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { DOMAINS, getDomain } from '../../data/domainRegistry.js';
import { useAllFindings } from '../../hooks/useDomainData.js';
import useExplainability from '../../hooks/useExplainability.js';
import { AGENT_META } from '../../data/agentMeta.js';
import { formatLkr } from '../../utils/domainAggregations.js';
import { Num } from '../../components/shared/ui.jsx';
import { useApp } from '../../context/AppContext.jsx';
import { fixtureCases } from '../../data/caseRegistry.js';
import { dedupedExposureBreakdown } from '../../utils/exposureDedup.js';
import ExplainabilityPanel from '../../components/business/ExplainabilityPanel.jsx';
import InfoHint from '../../components/business/InfoHint.jsx';
import HeatmapInsights from '../../components/business/HeatmapInsights.jsx';
import OrchestratorPanel from '../../components/business/OrchestratorPanel.jsx';
import CaseLifecycleInsights from '../../components/business/CaseLifecycleInsights.jsx';
import AsOfStamp from '../../components/business/AsOfStamp.jsx';
import { Map as MapIcon, ChevronRight, ChevronLeft, Sparkles } from 'lucide-react';

// ─── BUSINESS RISK HEATMAP (REDESIGNED) ──────────────────────────────────────
// Two-column layout: matrix on the left, selected-cell case list + inline
// explainability on the right. Clicking a cell selects it; clicking a case
// in the right-hand list loads its explainability underneath.

// Agent → Risk Category mapping (structural, not data)
const AGENT_TO_RISK_CATEGORY = {
  credit:         'Credit',
  transaction:    'Financial Crime',
  suspense:       'Operational',
  kyc:            'Compliance',
  controls:       'Operational',
  digital:        'Cyber & Fraud',
  trade:          'Financial Crime',
  insider:        'Conduct',
  mje:            'Financial Reporting',
  capital:        'Capital & Liquidity',
  balance:        'Capital & Liquidity',
  wealth:         'Conduct',
  collateral:     'Credit',
  connectedParty: 'Credit',
  alm:            'Market',
  thirdParty:     'Operational',
  accessRights:   'Cyber & Fraud',
  conduct:        'Conduct',
};

const RISK_CATEGORIES = [
  'Credit',
  'Market',
  'Capital & Liquidity',
  'Operational',
  'Financial Crime',
  'Compliance',
  'Cyber & Fraud',
  'Conduct',
  'Financial Reporting',
];

const CATEGORY_DESCRIPTIONS = {
  'Credit':              'Loan-book staging, collateral integrity, single-obligor and connected-party limits.',
  'Market':              'Interest rate risk in the banking book, ALM gaps, duration and sensitivity.',
  'Capital & Liquidity': 'Basel III ratios — Tier 1, Total CAR, LCR, NSFR — and balance-sheet drivers.',
  'Operational':         'Reconciliation ageing, branch controls, vendor concentration, outsourcing risk.',
  'Financial Crime':     'AML structuring, TBML, over-invoicing, duplicate LCs, transaction surveillance.',
  'Compliance':          'CDD/KYC integrity, sanctions hits, PEP EDD currency, FATF exposure.',
  'Cyber & Fraud':       'Account takeover, session anomalies, biometric deviation, access-rights drift.',
  'Conduct':             'Staff insider-risk behaviour, wealth mis-selling, recurring conduct events.',
  'Financial Reporting': 'Manual journal integrity, tax position testing, maker-checker breaches.',
};

export default function BusinessRiskHeatmap() {
  const navigate = useNavigate();
  const findings = useAllFindings();
  const { state } = useApp();
  const caseWorkbench = state.caseWorkbench || {};

  // Merge static cases with any generated by live agent runs so ageing
  // metrics below the matrix see the full population.
  const allCases = useMemo(() => {
    const generated = state.cases || [];
    const demoCases = fixtureCases(state); // fixtures only when the engine has no cases of its own
    const byId = new Set(demoCases.map(c => c.id));
    return [...demoCases, ...generated.filter(c => !byId.has(c.id))];
  }, [state.cases, state.demoMode]);

  const [selectedCell, setSelectedCell] = useState(null); // { domainId, category }
  const [selectedFindingIdx, setSelectedFindingIdx] = useState(0);

  // Build the matrix: (domain, category) → { criticals, highs, exposure, findings[] }
  const matrix = useMemo(() => {
    const m = {};
    for (const d of DOMAINS) {
      m[d.id] = {};
      for (const c of RISK_CATEGORIES) m[d.id][c] = { criticals: 0, highs: 0, mediums: 0, exposure: 0, findings: [] };
    }
    for (const f of findings) {
      const cat = AGENT_TO_RISK_CATEGORY[f.agentId] || 'Operational';
      const sev = (f.severity || 'medium').toLowerCase();
      const exp = f.finding?.affected_exposure_lkr || f.finding?.affected_balance_lkr || f.finding?.exposure_lkr || 0;
      for (const dom of f.domainTags || []) {
        const cell = m[dom]?.[cat];
        if (!cell) continue;
        if (sev === 'critical') cell.criticals++;
        else if (sev === 'high') cell.highs++;
        else if (sev === 'medium') cell.mediums++;
        cell.exposure += exp;
        cell.findings.push(f);
      }
    }
    return m;
  }, [findings]);

  // Entity-deduped flagged exposure — the same basis as Reports / Bank Position,
  // so the heatmap headline reconciles with them (a finding-summed total would
  // double-count an entity flagged by several agents).
  const entityExposure = useMemo(() => dedupedExposureBreakdown(findings).total, [findings]);

  const selectedFindings = selectedCell ? matrix[selectedCell.domainId]?.[selectedCell.category]?.findings || [] : [];
  const selectedFinding = selectedFindings[selectedFindingIdx];

  function onCellClick(domainId, category) {
    setSelectedCell({ domainId, category });
    setSelectedFindingIdx(0);
  }

  // Full-page subview when a cell is selected; otherwise full-width matrix.
  if (selectedCell) {
    return (
      <CellDrilldownPage
        cell={matrix[selectedCell.domainId][selectedCell.category]}
        domain={getDomain(selectedCell.domainId)}
        category={selectedCell.category}
        selectedFindings={selectedFindings}
        selectedFindingIdx={selectedFindingIdx}
        onSelectFinding={setSelectedFindingIdx}
        selectedFinding={selectedFinding}
        onBack={() => { setSelectedCell(null); setSelectedFindingIdx(0); }}
      />
    );
  }

  return (
    <div style={{ maxWidth: 1500, display: 'flex', flexDirection: 'column', gap: 14 }}>
      {/* 0. Live cross-agent orchestrator — only renders content once ≥2 agents have run. */}
      <OrchestratorPanel />

      {/* 1. Heatmap summary — derived metrics from the matrix below */}
      <HeatmapInsights
        matrix={matrix}
        entityExposure={entityExposure}
        onPickCell={onCellClick}
        onPickDomain={(id) => navigate(`/business-view/${id}`)}
      />

      {/* 2. The heatmap itself */}
      <Header />
      <Legend />

      <div style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-lg)', padding: 14, overflowX: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'separate', borderSpacing: 0, fontSize: 11 }}>
          <thead>
            <tr>
              <th style={{ ...thBase, position: 'sticky', left: 0, background: 'var(--color-surface)', zIndex: 2, minWidth: 200 }}>Domain</th>
              {RISK_CATEGORIES.map(c => (
                <th key={c} style={{ ...thBase, textAlign: 'center', minWidth: 90 }}>
                  <div style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}>
                    <div style={{ fontWeight: 800, color: 'var(--color-text-2)', fontSize: 9.5 }}>{c}</div>
                    <InfoHint text={CATEGORY_DESCRIPTIONS[c]} title={c} size={11} align="center" />
                  </div>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {DOMAINS.map(d => (
              <tr key={d.id}>
                <td
                  style={{ ...tdBase, position: 'sticky', left: 0, background: 'var(--color-surface)', zIndex: 1, minWidth: 200 }}
                >
                  <button
                    onClick={() => navigate(`/business-view/${d.id}`)}
                    style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, textAlign: 'left', width: '100%' }}
                    title={`Open ${d.label} deep-dive`}
                  >
                    <div style={{ fontWeight: 800, color: 'var(--color-text)', fontSize: 12 }}>{d.label}</div>
                    <div style={{ fontSize: 9.5, fontWeight: 700, color: 'var(--color-text-3)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{d.ownerRole}</div>
                  </button>
                </td>
                {RISK_CATEGORIES.map(c => {
                  const cell = matrix[d.id][c];
                  return (
                    <td key={c} style={{ ...tdBase, padding: 3, textAlign: 'center' }}>
                      <HeatCell
                        cell={cell}
                        domain={d}
                        category={c}
                        selected={false}
                        onClick={() => onCellClick(d.id, c)}
                      />
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* 3. Case lifecycle — derived from cases + stateHistory + workbench */}
      <CaseLifecycleInsights
        cases={allCases}
        caseWorkbench={caseWorkbench}
        navigate={navigate}
      />
    </div>
  );
}

// ─── HEADER ──────────────────────────────────────────────────────────────────
function Header() {
  return (
    <div>
      <h2 style={{ margin: 0, fontSize: 22, fontWeight: 800, letterSpacing: '-0.02em', display: 'flex', alignItems: 'center', gap: 10 }}>
        <MapIcon size={20} style={{ color: '#B45309' }} />
        Risk Heatmap
        <InfoHint
          title="Risk Heatmap"
          text="Every business domain (rows) crossed with every enterprise risk category (columns). Each cell counts the active agent findings in that intersection, coloured by the worst severity present. Click any cell to open a full deep-dive of its findings and explainability trails."
          size={15}
        />
      </h2>
      <p style={{ fontSize: 13, color: 'var(--color-text-2)', margin: '6px 0 0', maxWidth: 980, lineHeight: 1.55, display: 'flex', alignItems: 'baseline', gap: 4, flexWrap: 'wrap' }}>
        <span>Every business domain × every enterprise risk category. Click any cell to open the underlying findings and explainability in a dedicated subview.</span>
        <InfoHint
          title="How to read this heatmap"
          text="Rows are business domains, columns are enterprise risk categories. Each cell counts the active agent findings at that intersection; its colour is the highest severity present (red = a critical, amber = a high, yellow = medium only, green = covered and clean), and the number is that finding count. Click a cell to drill down to its findings and explainability."
          size={13}
          align="left"
        />
      </p>
      <div style={{ marginTop: 6 }}>
        <AsOfStamp source="Derived from current agent outputs" />
      </div>
    </div>
  );
}

const LEGEND_DESCRIPTIONS = {
  'Critical present': 'At least one critical-severity finding exists in this intersection. Cell intensity scales with critical count.',
  'High present':     'No criticals, but one or more high-severity findings are active. Cell intensity scales with high count.',
  'Medium only':      'Only medium-severity findings — monitor and action at next cycle, not an immediate breach.',
  'Covered · clean':  'At least one primary agent is watching this category for this domain AND is currently producing no findings here. Assurance: controls are looking, nothing is firing.',
  'Not covered':      'No primary agent is configured to produce findings in this category for this domain. Either the risk is out-of-scope for the domain, or coverage is missing — review agent-to-domain mapping in Engine Map.',
};

function Legend() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap', padding: '8px 14px', background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 10 }}>
      <div style={{ fontSize: 10.5, fontWeight: 800, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--color-text-3)' }}>Cells</div>
      <LegendItem color="rgba(196,30,58,0.5)" label="Critical present" />
      <LegendItem color="rgba(180,83,9,0.5)" label="High present" />
      <LegendItem color="rgba(202,138,4,0.35)" label="Medium only" />
      <LegendItem color="rgba(11,191,122,0.12)" label="Covered · clean" />
      <LegendItem color="rgba(200,200,200,0.12)" label="Not covered" />
    </div>
  );
}

function LegendItem({ color, label }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
      <span style={{ width: 14, height: 14, borderRadius: 3, background: color, border: '1px solid var(--color-border)' }} />
      <span style={{ fontSize: 11, color: 'var(--color-text-2)' }}>{label}</span>
      <InfoHint text={LEGEND_DESCRIPTIONS[label]} title={label} size={11} align="center" />
    </div>
  );
}

// ─── HEAT CELL ───────────────────────────────────────────────────────────────
function HeatCell({ cell, domain, category, selected, onClick }) {
  const { criticals = 0, highs = 0, mediums = 0, exposure = 0 } = cell;
  const total = criticals + highs + mediums;
  const primaryAgents = domain.agentsPrimary || [];
  const theoreticallyCovered = primaryAgents.some(a => AGENT_TO_RISK_CATEGORY[a] === category);

  let bg, fg;
  if (total === 0) {
    bg = theoreticallyCovered ? 'rgba(11,191,122,0.12)' : 'rgba(200,200,200,0.10)';
    fg = theoreticallyCovered ? '#0BBF7A' : 'var(--color-text-3)';
  } else if (criticals > 0) {
    const intensity = Math.min(0.9, 0.35 + criticals * 0.18);
    bg = `rgba(196,30,58,${intensity})`;
    fg = 'white';
  } else if (highs > 0) {
    const intensity = Math.min(0.85, 0.3 + highs * 0.14);
    bg = `rgba(180,83,9,${intensity})`;
    fg = 'white';
  } else {
    bg = 'rgba(202,138,4,0.35)';
    fg = '#713F12';
  }

  const border = selected ? '2px solid #F5B841' : '1px solid rgba(0,0,0,0.05)';

  return (
    <button
      onClick={onClick}
      title={`${domain.label} · ${category}${exposure > 0 ? '\nExposure: ' + formatLkr(exposure) : ''}`}
      style={{
        width: 72, height: 52, borderRadius: 6, cursor: total > 0 ? 'pointer' : 'default',
        background: bg, color: fg, border,
        fontFamily: 'var(--font-display)',
        display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
        padding: 0, transition: 'transform 0.12s',
        boxShadow: selected ? '0 0 0 3px rgba(245,184,65,0.2)' : 'none',
      }}
      disabled={total === 0}
    >
      {total === 0 ? (
        <span style={{ fontSize: 13, opacity: 0.5 }}>—</span>
      ) : (
        <>
          {criticals > 0 && (
            <div style={{ fontSize: 11, fontWeight: 800, lineHeight: 1.1 }}>
              {criticals} <span style={{ fontSize: 9, fontWeight: 700, opacity: 0.85 }}>crit</span>
            </div>
          )}
          {highs > 0 && (
            <div style={{ fontSize: 10.5, fontWeight: 700, lineHeight: 1.1, opacity: 0.95 }}>
              {highs} <span style={{ fontSize: 9, opacity: 0.85 }}>high</span>
            </div>
          )}
          {criticals === 0 && highs === 0 && mediums > 0 && (
            <div style={{ fontSize: 10.5, fontWeight: 700 }}>
              {mediums} <span style={{ fontSize: 9, opacity: 0.8 }}>med</span>
            </div>
          )}
        </>
      )}
    </button>
  );
}

// ─── CELL DRILLDOWN — FULL-PAGE SUBVIEW ──────────────────────────────────────
function CellDrilldownPage({ cell, domain, category, selectedFindings, selectedFindingIdx, onSelectFinding, selectedFinding, onBack }) {
  const navigate = useNavigate();
  const exposure = cell.exposure || 0;
  const { criticals = 0, highs = 0, mediums = 0 } = cell;

  return (
    <div style={{ maxWidth: 1500, display: 'flex', flexDirection: 'column', gap: 16 }}>
      {/* Breadcrumb back-button */}
      <button
        onClick={onBack}
        style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'none', border: 'none', color: 'var(--color-text-3)', cursor: 'pointer', fontSize: 12, fontWeight: 600, padding: 0, width: 'fit-content' }}
      >
        <ChevronLeft size={14} /> Back to heatmap
      </button>

      {/* Cell header */}
      <div style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-lg)', padding: '16px 20px' }}>
        <div style={{ fontSize: 10.5, fontWeight: 800, letterSpacing: '0.09em', textTransform: 'uppercase', color: '#B45309' }}>
          Heatmap cell deep-dive
        </div>
        <h2 style={{ margin: '6px 0 0', fontSize: 22, fontWeight: 800, letterSpacing: '-0.02em', display: 'flex', alignItems: 'center', gap: 10 }}>
          {domain.label} <span style={{ color: 'var(--color-text-3)', fontWeight: 600 }}>·</span> {category}
          <InfoHint title={category} text={CATEGORY_DESCRIPTIONS[category]} size={14} />
        </h2>
        <p style={{ fontSize: 13, color: 'var(--color-text-2)', margin: '8px 0 0', maxWidth: 900, lineHeight: 1.55 }}>
          {selectedFindings.length} finding{selectedFindings.length !== 1 ? 's' : ''} tie{selectedFindings.length === 1 ? 's' : ''} this risk category to this domain. Select a finding on the left to see its full explainability trail.
        </p>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 12, flexWrap: 'wrap' }}>
          {criticals > 0 && <span style={{ display: 'inline-flex', alignItems: 'center', fontSize: 11, fontWeight: 800, padding: '2px 8px', borderRadius: 10, background: 'rgba(196,30,58,0.12)', color: '#C41E3A', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{criticals} critical<InfoHint title="Critical findings" text="Count of critical-severity agent findings in this domain × category cell. Severity is set deterministically by the rule that fired — not a judgement — so this number is reproducible from the same data." size={11} align="center" /></span>}
          {highs > 0 && <span style={{ display: 'inline-flex', alignItems: 'center', fontSize: 11, fontWeight: 800, padding: '2px 8px', borderRadius: 10, background: 'rgba(180,83,9,0.12)', color: '#B45309', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{highs} high<InfoHint title="High findings" text="Count of high-severity findings in this cell. Each was raised by a deterministic rule crossing its threshold; the band is fixed by that rule, not estimated." size={11} align="center" /></span>}
          {mediums > 0 && <span style={{ display: 'inline-flex', alignItems: 'center', fontSize: 11, fontWeight: 800, padding: '2px 8px', borderRadius: 10, background: 'rgba(202,138,4,0.12)', color: '#185FA5', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{mediums} medium<InfoHint title="Medium findings" text="Count of medium-severity findings in this cell — monitor-and-action items rather than immediate breaches. Severity is rule-assigned and reproducible." size={11} align="center" /></span>}
          {exposure > 0 && <span style={{ display: 'inline-flex', alignItems: 'center', fontSize: 11.5, fontWeight: 800, color: 'var(--color-text-2)', fontFamily: 'var(--font-display)' }}>Exposure · <Num>{formatLkr(exposure)}</Num><InfoHint title="Exposure" text="Sum of the LKR amounts attached to the findings in this cell (affected exposure, balance or transaction value). Cell-level, so it can overlap exposure shown in other cells when one entity is flagged across several." size={11} align="center" /></span>}
          <button
            onClick={() => navigate(`/business-view/${domain.id}`)}
            style={{ marginLeft: 'auto', fontSize: 11, fontWeight: 700, padding: '5px 12px', borderRadius: 10, background: 'rgba(245,184,65,0.12)', color: '#B45309', border: '1px solid rgba(245,184,65,0.3)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4 }}
          >
            Open {domain.label} deep-dive <ChevronRight size={12} />
          </button>
        </div>
      </div>

      {/* Findings list (left) + explainability (right, full remaining width) */}
      <div style={{ display: 'grid', gridTemplateColumns: '340px 1fr', gap: 16, alignItems: 'flex-start' }}>
        <FindingsMiniList
          findings={selectedFindings}
          selectedIdx={selectedFindingIdx}
          onSelect={onSelectFinding}
        />
        <div style={{ background: 'var(--color-surface-2)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-lg)', padding: 18, minHeight: 600 }}>
          {selectedFinding ? (
            <HeatmapExplainSlot item={selectedFinding} />
          ) : (
            <div style={{ fontSize: 11.5, color: 'var(--color-text-3)', fontStyle: 'italic', padding: 16 }}>
              No findings in this cell.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function HeatmapExplainSlot({ item }) {
  const { loading, source, data, error } = useExplainability(item.agentId, item.findingIndex, item.finding);
  return (
    <ExplainabilityPanel
      loading={loading}
      source={source}
      data={data}
      error={error}
      finding={item.finding}
      agentId={item.agentId}
    />
  );
}

function FindingsMiniList({ findings, selectedIdx, onSelect }) {
  return (
    <div style={{ background: 'var(--color-surface-2)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-lg)', padding: 10, maxHeight: 720, overflowY: 'auto' }}>
      <div style={{ fontSize: 10.5, fontWeight: 800, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--color-text-3)', padding: '4px 6px 10px' }}>
        {findings.length} finding{findings.length !== 1 ? 's' : ''}
      </div>
      {findings.length === 0 && (
        <div style={{ padding: 14, fontSize: 11.5, color: 'var(--color-text-3)', textAlign: 'center', fontStyle: 'italic' }}>
          Empty cell.
        </div>
      )}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {findings.map((f, i) => {
          const sev = (f.severity || 'medium').toLowerCase();
          const sevColor = sev === 'critical' ? '#C41E3A' : sev === 'high' ? '#B45309' : '#185FA5';
          const text = f.finding?.finding || f.finding?.explanation || f.finding?.pattern_detected || '';
          const agentMeta = AGENT_META[f.agentId];
          const selected = selectedIdx === i;
          return (
            <button
              key={i}
              onClick={() => onSelect(i)}
              style={{
                display: 'block', width: '100%', textAlign: 'left',
                padding: '12px 14px',
                background: selected ? 'white' : 'var(--color-surface)',
                border: `1px solid ${selected ? 'rgba(245,184,65,0.45)' : 'var(--color-border)'}`,
                borderLeft: `4px solid ${sevColor}`,
                borderRadius: 8,
                boxShadow: selected ? '0 2px 6px rgba(245,184,65,0.15)' : 'none',
                cursor: 'pointer', transition: 'all 0.12s',
                fontFamily: 'inherit',
              }}
            >
              <div style={{ display: 'flex', gap: 6, marginBottom: 6, alignItems: 'center' }}>
                <span style={{ fontSize: 9, fontWeight: 800, padding: '1px 6px', borderRadius: 6, background: sevColor + '18', color: sevColor, textTransform: 'uppercase', letterSpacing: '0.04em' }}>{sev}</span>
                {agentMeta && (
                  <span style={{ fontSize: 9, fontWeight: 700, color: agentMeta.color, textTransform: 'uppercase', letterSpacing: '0.04em' }}>{agentMeta.name}</span>
                )}
              </div>
              <div style={{ fontSize: 11.5, color: selected ? 'var(--color-text)' : 'var(--color-text-2)', lineHeight: 1.5, fontWeight: selected ? 600 : 500 }}>
                {truncate(text, 140)}
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}

function truncate(s, n) { if (!s) return ''; return s.length > n ? s.slice(0, n - 1).trim() + '…' : s; }

const thBase = { padding: '8px 8px', textAlign: 'left', fontSize: 9.5, fontWeight: 800, letterSpacing: '0.06em', textTransform: 'uppercase', color: 'var(--color-text-3)', borderBottom: '2px solid var(--color-border)' };
const tdBase = { padding: '6px 5px', borderBottom: '1px solid var(--color-border)', verticalAlign: 'middle' };
